# Netlify Configuration for DigiBoard Admin Dashboard
[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_ENV = "production"
  NETLIFY = "true"

# Handle all routes through the serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/public/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
